-- First, let's clear the colleges table and add proper sample data for J&K colleges
DELETE FROM colleges;

-- Insert sample colleges data for Jammu & Kashmir
INSERT INTO colleges ("College Name", "Type", "District", "Urban/Rural Status", "Courses Offered (Categorized Streams)", "Working College Link") VALUES
('University of Jammu', 'Government University', 'Jammu', 'Urban', 'Engineering, Medical, Commerce, Science, Arts, Law, Management', 'https://jammuuniversity.ac.in'),
('Islamic University of Science & Technology', 'Private University', 'Pulwama', 'Rural', 'Engineering, Medical, Commerce, Management, IT', 'https://iust.ac.in'),
('Sher-e-Kashmir University of Agricultural Sciences and Technology', 'Government University', 'Jammu', 'Urban', 'Agriculture, Veterinary Science, Forestry, Food Technology', 'https://skuast.org'),
('Central University of Jammu', 'Central Government University', 'Samba', 'Rural', 'Engineering, Science, Arts, Commerce, Management, Law', 'https://cujammu.ac.in'),
('NIT Srinagar', 'Central Government Institute', 'Srinagar', 'Urban', 'Engineering, Technology, Computer Science', 'https://nitsri.ac.in'),
('Government Medical College Jammu', 'Government Medical College', 'Jammu', 'Urban', 'Medical, Nursing, Pharmacy', 'https://gmcjammu.nic.in'),
('Government Medical College Srinagar', 'Government Medical College', 'Srinagar', 'Urban', 'Medical, Nursing, Pharmacy, Dental', 'https://gmcsrinagar.edu.in'),
('Government College of Engineering and Technology', 'Government Engineering College', 'Jammu', 'Urban', 'Engineering, Technology, Computer Science', 'https://gcetjammu.ac.in'),
('Kashmir University', 'Government University', 'Srinagar', 'Urban', 'Engineering, Medical, Science, Arts, Commerce, Law, Management', 'https://kashmiruniversity.net'),
('SMVD University', 'Private University', 'Katra', 'Rural', 'Engineering, Management, Pharmacy, Nursing', 'https://smvdu.ac.in'),
('Government Degree College Anantnag', 'Government College', 'Anantnag', 'Urban', 'Science, Commerce, Arts', NULL),
('Government Degree College Baramulla', 'Government College', 'Baramulla', 'Urban', 'Science, Commerce, Arts', NULL),
('Government Degree College Kupwara', 'Government College', 'Kupwara', 'Rural', 'Science, Commerce, Arts', NULL),
('Government Degree College Ganderbal', 'Government College', 'Ganderbal', 'Rural', 'Science, Commerce, Arts', NULL),
('Government Degree College Kulgam', 'Government College', 'Kulgam', 'Rural', 'Science, Commerce, Arts', NULL),
('Lovely Professional University Campus', 'Private University', 'Jammu', 'Urban', 'Engineering, Management, Commerce, Arts', 'https://lpu.in'),
('Baba Ghulam Shah Badshah University', 'Government University', 'Rajouri', 'Rural', 'Engineering, Science, Arts, Commerce, Management', 'https://bgsbu.ac.in'),
('Government College for Women', 'Government College', 'Srinagar', 'Urban', 'Science, Commerce, Arts', NULL),
('Cluster University Jammu', 'Government University', 'Jammu', 'Urban', 'Science, Commerce, Arts, Management', 'https://cujammu.ac.in'),
('Cluster University Srinagar', 'Government University', 'Srinagar', 'Urban', 'Science, Commerce, Arts, Management', 'https://cusrinagar.edu.in'),
('Government Degree College Udhampur', 'Government College', 'Udhampur', 'Rural', 'Science, Commerce, Arts', NULL),
('Government Degree College Doda', 'Government College', 'Doda', 'Rural', 'Science, Commerce, Arts', NULL),
('Government Degree College Kathua', 'Government College', 'Kathua', 'Urban', 'Science, Commerce, Arts', NULL),
('Government Degree College Poonch', 'Government College', 'Poonch', 'Rural', 'Science, Commerce, Arts', NULL),
('Government Degree College Reasi', 'Government College', 'Reasi', 'Rural', 'Science, Commerce, Arts', NULL),
('Amar Singh College', 'Private College', 'Srinagar', 'Urban', 'Commerce, Arts, Management', NULL),
('Women''s College Srinagar', 'Government College', 'Srinagar', 'Urban', 'Science, Commerce, Arts', NULL),
('Government Degree College Budgam', 'Government College', 'Budgam', 'Rural', 'Science, Commerce, Arts', NULL),
('Government Degree College Pulwama', 'Government College', 'Pulwama', 'Rural', 'Science, Commerce, Arts', NULL),
('Government Degree College Shopian', 'Government College', 'Shopian', 'Rural', 'Science, Commerce, Arts', NULL),
('IIIM Jammu', 'Central Government Institute', 'Jammu', 'Urban', 'Science, Research, Biotechnology', 'https://iiim.ac.in'),
('IIT Jammu', 'Central Government Institute', 'Jammu', 'Urban', 'Engineering, Technology, Computer Science', 'https://iitjammu.ac.in'),
('Government Polytechnic Jammu', 'Government Polytechnic', 'Jammu', 'Urban', 'Engineering, Technology, Computer Applications', NULL),
('Government Polytechnic Srinagar', 'Government Polytechnic', 'Srinagar', 'Urban', 'Engineering, Technology, Computer Applications', NULL),
('Government ITI Jammu', 'Government ITI', 'Jammu', 'Urban', 'Vocational, Technical, Skill Development', NULL);